<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/auth.proto

namespace Endpoints\Examples\Bookstore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * A book resource.
 * </pre>
 *
 * Protobuf type <code>endpoints.examples.bookstore.Book</code>
 */
class Book extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * A unique book id.
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    private $id = 0;
    /**
     * <pre>
     * An author of the book.
     * </pre>
     *
     * <code>string author = 2;</code>
     */
    private $author = '';
    /**
     * <pre>
     * A book title.
     * </pre>
     *
     * <code>string title = 3;</code>
     */
    private $title = '';

    public function __construct() {
        \GPBMetadata\Protos\Auth::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * A unique book id.
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <pre>
     * A unique book id.
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;
    }

    /**
     * <pre>
     * An author of the book.
     * </pre>
     *
     * <code>string author = 2;</code>
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * <pre>
     * An author of the book.
     * </pre>
     *
     * <code>string author = 2;</code>
     */
    public function setAuthor($var)
    {
        GPBUtil::checkString($var, True);
        $this->author = $var;
    }

    /**
     * <pre>
     * A book title.
     * </pre>
     *
     * <code>string title = 3;</code>
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * <pre>
     * A book title.
     * </pre>
     *
     * <code>string title = 3;</code>
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;
    }

}

