<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/auth.proto

namespace Endpoints\Examples\Bookstore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request message for CreateShelf method.
 * </pre>
 *
 * Protobuf type <code>endpoints.examples.bookstore.CreateShelfRequest</code>
 */
class CreateShelfRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The shelf resource to create.
     * </pre>
     *
     * <code>.endpoints.examples.bookstore.Shelf shelf = 1;</code>
     */
    private $shelf = null;

    public function __construct() {
        \GPBMetadata\Protos\Auth::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The shelf resource to create.
     * </pre>
     *
     * <code>.endpoints.examples.bookstore.Shelf shelf = 1;</code>
     */
    public function getShelf()
    {
        return $this->shelf;
    }

    /**
     * <pre>
     * The shelf resource to create.
     * </pre>
     *
     * <code>.endpoints.examples.bookstore.Shelf shelf = 1;</code>
     */
    public function setShelf(&$var)
    {
        GPBUtil::checkMessage($var, \Endpoints\Examples\Bookstore\Shelf::class);
        $this->shelf = $var;
    }

}

