<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/auth.proto

namespace Endpoints\Examples\Bookstore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request message for CreateBook method.
 * </pre>
 *
 * Protobuf type <code>endpoints.examples.bookstore.CreateBookRequest</code>
 */
class CreateBookRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The ID of the shelf on which to create a book.
     * </pre>
     *
     * <code>int64 shelf = 1;</code>
     */
    private $shelf = 0;
    /**
     * <pre>
     * A book resource to create on the shelf.
     * </pre>
     *
     * <code>.endpoints.examples.bookstore.Book book = 2;</code>
     */
    private $book = null;

    public function __construct() {
        \GPBMetadata\Protos\Auth::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The ID of the shelf on which to create a book.
     * </pre>
     *
     * <code>int64 shelf = 1;</code>
     */
    public function getShelf()
    {
        return $this->shelf;
    }

    /**
     * <pre>
     * The ID of the shelf on which to create a book.
     * </pre>
     *
     * <code>int64 shelf = 1;</code>
     */
    public function setShelf($var)
    {
        GPBUtil::checkInt64($var);
        $this->shelf = $var;
    }

    /**
     * <pre>
     * A book resource to create on the shelf.
     * </pre>
     *
     * <code>.endpoints.examples.bookstore.Book book = 2;</code>
     */
    public function getBook()
    {
        return $this->book;
    }

    /**
     * <pre>
     * A book resource to create on the shelf.
     * </pre>
     *
     * <code>.endpoints.examples.bookstore.Book book = 2;</code>
     */
    public function setBook(&$var)
    {
        GPBUtil::checkMessage($var, \Endpoints\Examples\Bookstore\Book::class);
        $this->book = $var;
    }

}

