<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/auth.proto

namespace Endpoints\Examples\Bookstore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request message for DeleteBook method.
 * </pre>
 *
 * Protobuf type <code>endpoints.examples.bookstore.DeleteBookRequest</code>
 */
class DeleteBookRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The ID of the shelf from which to delete a book.
     * </pre>
     *
     * <code>int64 shelf = 1;</code>
     */
    private $shelf = 0;
    /**
     * <pre>
     * The ID of the book to delete.
     * </pre>
     *
     * <code>int64 book = 2;</code>
     */
    private $book = 0;

    public function __construct() {
        \GPBMetadata\Protos\Auth::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The ID of the shelf from which to delete a book.
     * </pre>
     *
     * <code>int64 shelf = 1;</code>
     */
    public function getShelf()
    {
        return $this->shelf;
    }

    /**
     * <pre>
     * The ID of the shelf from which to delete a book.
     * </pre>
     *
     * <code>int64 shelf = 1;</code>
     */
    public function setShelf($var)
    {
        GPBUtil::checkInt64($var);
        $this->shelf = $var;
    }

    /**
     * <pre>
     * The ID of the book to delete.
     * </pre>
     *
     * <code>int64 book = 2;</code>
     */
    public function getBook()
    {
        return $this->book;
    }

    /**
     * <pre>
     * The ID of the book to delete.
     * </pre>
     *
     * <code>int64 book = 2;</code>
     */
    public function setBook($var)
    {
        GPBUtil::checkInt64($var);
        $this->book = $var;
    }

}

