<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/auth.proto

namespace Endpoints\Examples\Bookstore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response message to ListBooks method.
 * </pre>
 *
 * Protobuf type <code>endpoints.examples.bookstore.ListBooksResponse</code>
 */
class ListBooksResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The books on the shelf.
     * </pre>
     *
     * <code>repeated .endpoints.examples.bookstore.Book books = 1;</code>
     */
    private $books;

    public function __construct() {
        \GPBMetadata\Protos\Auth::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The books on the shelf.
     * </pre>
     *
     * <code>repeated .endpoints.examples.bookstore.Book books = 1;</code>
     */
    public function getBooks()
    {
        return $this->books;
    }

    /**
     * <pre>
     * The books on the shelf.
     * </pre>
     *
     * <code>repeated .endpoints.examples.bookstore.Book books = 1;</code>
     */
    public function setBooks(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Endpoints\Examples\Bookstore\Book::class);
        $this->books = $var;
    }

}

